### ISSUE TITLE
Role does not activate changes in check_mk

### ISSUE THREAD

**Issue by wezelboy** [elnappo/ansible-role-check-mk-agent#10]
Unless I'm mistaken, library/check_mk.py line 241:

```python
if a_module.params["activate_changes"]:
    if result["changed"] == True:
        result["activate_changes"] = cmk.activate_changes()
```

should be:

```python
if a_module.params["activate_changes"]:
    result["changed"] = True
    result["activate_changes"] = cmk.activate_changes()
```

**Comment by wezelboy** [comment]
The indentation is messed up in the above examples.

**Comment by FleischKarussel** [comment]
Hello @elnappo,

could you please merge this fix, I just slipped over it.
And many thanks to @wezelboy for fixing things.

Thanks to both of you!

Br
FK

**Comment by elnappo** [comment]
Sorry for the late response, almost forget about that. I wanted to test this change but I didn't had time. Will merge it now! Many thanks to you two!

**Comment by elnappo** [comment]
I issued a new release [v2.2.1](https://github.com/elnappo/ansible-role-check-mk-agent/releases/tag/v2.2.1), cloud you confirm it is working as expected?

**Comment by FleischKarussel** [comment]
> 
> 
> I issued a new release [v2.2.1](https://github.com/elnappo/ansible-role-check-mk-agent/releases/tag/v2.2.1), cloud you confirm it is working as expected?

Hey @elnappo,

I can confirm this is working fine.

Thanks

**Comment by elnappo** [comment]
Thank you! Closing this one :)
