### ISSUE TITLE
Ansible Galaxy Role is not up to date

### ISSUE THREAD

**Issue by jp1337** [elnappo/ansible-role-check-mk-agent#17]
Hi there!
I just started using this role and noticed, that the version on galaxy has issues that are already fixed.
Using the role I got issue #15 again.
Now I switched to the github repo instead.

**Comment by elnappo** [comment]
Thanks for reporting, I released [v2.3.0](https://github.com/elnappo/ansible-role-check-mk-agent/releases/tag/v2.3.0) which is now available in Ansible galaxy.
