### ISSUE TITLE
install offline without access to ansible galaxy

### ISSUE THREAD

**Issue by ChrisPea** [elnappo/ansible-role-check-mk-agent#28]
how to install offline without access to ansible galaxy?

**Comment by jp1337** [comment]
that is a easy question, but the wrong place to ask.
Nevertheless here is the answer:
You can download the whole Git Repository as zip file and extract it into your roles folder. As an alternative you also could clone it to the roles folder for better updating.

**Comment by elnappo** [comment]
thanks @jpylypiw
