### ISSUE TITLE
Add host to check_mk instance via WATO API  failed

### ISSUE THREAD

**Issue by ramuskay** [elnappo/ansible-role-check-mk-agent#7]
Hi,

I've got this error when i start the playbook at the task Add host to check_mk instance via WATO API  : 
fatal: [devprod.exemple.com -> localhost]: FAILED! => {"changed": false, "msg": "requests library is required for this module"}

I am in python version 2.7.5
I think it is failing right there in the file library/check_mk.py (line 197): 

    a_module = AnsibleModule(argument_spec=argument_spec, supports_check_mode=False)
    if not REQUESTS_FOUND:
        a_module.fail_json(msg='requests library is required for this module')

**Comment by ramuskay** [comment]
Solved ! 
I had just to install the required module aka requests
```console
root@testrhel:/etc/ansible/# pip install requests
```

Maybe add it to the Requirements in the README ?

**Comment by elnappo** [comment]
Glad you found the solution yourself. The requirement is referenced in the `README.md` at https://github.com/elnappo/ansible-role-check-mk-agent#requirements

If you have further questions, I'm here ;) Would love to get some feedback for this role.
